/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.consultas;

import dominio.Factura;
import dominio.Libro;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vale_
 */
public class VentanaConsultaVentas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultaVentas
     */
    public VentanaConsultaVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblISBN = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTituloLibro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistroVentas = new javax.swing.JTable();
        lblEjemplaresVendidos = new javax.swing.JLabel();
        lblTotalRecaudado = new javax.swing.JLabel();
        lblTotalGanancia = new javax.swing.JLabel();
        lblCantEjemplaresVendidos = new javax.swing.JLabel();
        lblCantTotalRecaudado = new javax.swing.JLabel();
        lblCantTotalGanancia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Ventas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lblISBN.setText("Isbn");
        jPanel1.add(lblISBN);
        lblISBN.setBounds(20, 20, 20, 15);
        jPanel1.add(txtIsbn);
        txtIsbn.setBounds(70, 20, 70, 20);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar);
        btnConsultar.setBounds(300, 10, 110, 25);

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportar);
        btnExportar.setBounds(425, 10, 110, 25);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 20, 20, 20);

        lblTituloLibro.setText("Titulo Libro");
        jPanel1.add(lblTituloLibro);
        lblTituloLibro.setBounds(20, 60, 100, 15);

        tableRegistroVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Factura", "Cantidad", "Precio", "Importe"
            }
        ));
        jScrollPane1.setViewportView(tableRegistroVentas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 520, 130);

        lblEjemplaresVendidos.setText("Ejemplares vendidos");
        jPanel1.add(lblEjemplaresVendidos);
        lblEjemplaresVendidos.setBounds(50, 250, 140, 15);

        lblTotalRecaudado.setText("Total Recaudado");
        jPanel1.add(lblTotalRecaudado);
        lblTotalRecaudado.setBounds(220, 250, 110, 15);

        lblTotalGanancia.setText("Total Ganancia");
        jPanel1.add(lblTotalGanancia);
        lblTotalGanancia.setBounds(420, 250, 100, 15);

        lblCantEjemplaresVendidos.setText("cantidad");
        jPanel1.add(lblCantEjemplaresVendidos);
        lblCantEjemplaresVendidos.setBounds(70, 280, 60, 15);

        lblCantTotalRecaudado.setText("cantidad");
        jPanel1.add(lblCantTotalRecaudado);
        lblCantTotalRecaudado.setBounds(240, 280, 50, 15);

        lblCantTotalGanancia.setText("cantidad");
        jPanel1.add(lblCantTotalGanancia);
        lblCantTotalGanancia.setBounds(430, 280, 80, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 12, 550, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
 String isbn = txtIsbn.getText().trim();

    // Validar si el ISBN está vacío
    if (isbn.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un ISBN.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Buscar el libro por ISBN
    Libro libro = Libro.obtenerLibros().stream()
            .filter(l -> l.getIsbn().equals(isbn))
            .findFirst()
            .orElse(null);

    if (libro == null) {
        JOptionPane.showMessageDialog(this, "No se encontró un libro con el ISBN ingresado.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    lblTituloLibro.setText("Título: " + libro.getTitulo());

    // Obtener ventas del libro por ISBN
//    List<Factura> ventas = Factura.obtenerVentasPorIsbn(isbn);
//
//    if (ventas.isEmpty()) {
//        JOptionPane.showMessageDialog(this, "No hay ventas registradas para este libro.", "Información", JOptionPane.INFORMATION_MESSAGE);
//        return;
//    }
//
//    // Mostrar ventas en la tabla
//    DefaultTableModel model = (DefaultTableModel) tableRegistroVentas.getModel();
//    model.setRowCount(0); // Limpiar la tabla antes de agregar nuevas filas
//
//    int totalEjemplares = 0;
//    double totalRecaudado = 0.0;
//    double totalGanancia = 0.0;

//    for (Factura venta : ventas) {
//        for (Map.Entry<String, Integer> entry : venta.getLibrosVendidos().entrySet()) {
//            if (entry.getKey().equals(isbn)) {
//                int cantidad = entry.getValue();
//                double precioVenta = libro.getPrecioVenta();
//                double importe = cantidad * precioVenta;
//
//                // Agregar datos a la tabla
//                model.addRow(new Object[]{
//                        venta.getFecha(),
//                        venta.getCliente(),
//                        venta.getNumeroFactura(),
//                        cantidad,
//                        String.format("$%.2f", precioVenta),
//                        String.format("$%.2f", importe)
//                });
//
//                // Actualizar totales
//                totalEjemplares += cantidad;
//                totalRecaudado += importe;
//                totalGanancia += (precioVenta - libro.getPrecioCosto()) * cantidad;
//            }
//        }
//    }
//
//    // Mostrar resumen
//    lblCantEjemplaresVendidos.setText(String.valueOf(totalEjemplares));
//    lblCantTotalRecaudado.setText(String.format("$%.2f", totalRecaudado));
//    lblCantTotalGanancia.setText(String.format("$%.2f", totalGanancia));
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
try (PrintWriter writer = new PrintWriter(new File("VENTAS.CSV"))) {
        DefaultTableModel model = (DefaultTableModel) tableRegistroVentas.getModel();

        // Escribir encabezados
        writer.println("Fecha;Cliente;Factura;Cantidad;Precio;Importe");

        // Escribir filas de la tabla
        for (int i = 0; i < model.getRowCount(); i++) {
            writer.printf("%s;%s;%s;%s;%s;%s%n",
                    model.getValueAt(i, 0), // Fecha
                    model.getValueAt(i, 1), // Cliente
                    model.getValueAt(i, 2), // Factura
                    model.getValueAt(i, 3), // Cantidad
                    model.getValueAt(i, 4), // Precio
                    model.getValueAt(i, 5)  // Importe
            );
        }

        JOptionPane.showMessageDialog(this, "Ventas exportadas correctamente a VENTAS.CSV.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al exportar las ventas.", "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantEjemplaresVendidos;
    private javax.swing.JLabel lblCantTotalGanancia;
    private javax.swing.JLabel lblCantTotalRecaudado;
    private javax.swing.JLabel lblEjemplaresVendidos;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JLabel lblTotalGanancia;
    private javax.swing.JLabel lblTotalRecaudado;
    private javax.swing.JTable tableRegistroVentas;
    private javax.swing.JTextField txtIsbn;
    // End of variables declaration//GEN-END:variables
}
