/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz.consultas;

import dominio.Factura;
import dominio.Libro;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vale_
 */
public class VentanaConsultaVentas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultaVentas
     */
    public VentanaConsultaVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblISBN = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblTituloLibro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroVentas = new javax.swing.JTable();
        lblEjemplaresVendidos = new javax.swing.JLabel();
        lblTotalRecaudado = new javax.swing.JLabel();
        lblTotalGanancia = new javax.swing.JLabel();
        lblCantEjemplaresVendidos = new javax.swing.JLabel();
        lblCantTotalRecaudado = new javax.swing.JLabel();
        lblCantTotalGanancia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Ventas");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lblISBN.setText("Isbn");
        jPanel1.add(lblISBN);
        lblISBN.setBounds(20, 20, 50, 15);
        jPanel1.add(txtIsbn);
        txtIsbn.setBounds(70, 20, 70, 20);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar);
        btnConsultar.setBounds(300, 10, 110, 25);

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportar);
        btnExportar.setBounds(425, 10, 110, 25);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 20, 20, 20);

        lblTituloLibro.setText("Titulo Libro");
        jPanel1.add(lblTituloLibro);
        lblTituloLibro.setBounds(20, 60, 260, 15);

        tblRegistroVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Cliente", "Factura", "Cantidad", "Precio", "Importe"
            }
        ));
        jScrollPane1.setViewportView(tblRegistroVentas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 520, 130);

        lblEjemplaresVendidos.setText("Ejemplares vendidos");
        jPanel1.add(lblEjemplaresVendidos);
        lblEjemplaresVendidos.setBounds(50, 250, 140, 15);

        lblTotalRecaudado.setText("Total Recaudado");
        jPanel1.add(lblTotalRecaudado);
        lblTotalRecaudado.setBounds(220, 250, 110, 15);

        lblTotalGanancia.setText("Total Ganancia");
        jPanel1.add(lblTotalGanancia);
        lblTotalGanancia.setBounds(420, 250, 100, 15);

        lblCantEjemplaresVendidos.setText("cantidad");
        jPanel1.add(lblCantEjemplaresVendidos);
        lblCantEjemplaresVendidos.setBounds(70, 280, 60, 15);

        lblCantTotalRecaudado.setText("cantidad");
        jPanel1.add(lblCantTotalRecaudado);
        lblCantTotalRecaudado.setBounds(240, 280, 50, 15);

        lblCantTotalGanancia.setText("cantidad");
        jPanel1.add(lblCantTotalGanancia);
        lblCantTotalGanancia.setBounds(430, 280, 80, 15);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 12, 550, 340);

        setBounds(0, 0, 610, 417);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String isbn = txtIsbn.getText().trim();

        if (isbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un código ISBN para consultar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar el libro por ISBN para obtener su título
        Libro libroBuscado = Libro.obtenerLibroPorIsbn(isbn);
        if (libroBuscado == null) {
            JOptionPane.showMessageDialog(this, "No se encontró un libro con el ISBN ingresado.", "Información", JOptionPane.INFORMATION_MESSAGE);
            lblTituloLibro.setText("");
            tblRegistroVentas.setVisible(false);
            return;
        }

        // Actualizar el título del libro
        lblTituloLibro.setText(libroBuscado.getTitulo());

        // Buscar facturas que contengan este libro
        List<Factura> ventasPorIsbn = Factura.obtenerFacturas().values().stream()
                .filter(factura -> factura.getLibros().stream().anyMatch(libro -> {
            String[] partes = libro.split("x ");
            if (partes.length > 1) {
                String titulo = partes[1];
                return titulo.equals(libroBuscado.getTitulo());
            }
            return false;
        }))
                .sorted(Comparator.comparingInt(Factura::getNumeroFactura).reversed())
                .collect(Collectors.toList());

        if (ventasPorIsbn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se encontraron ventas para el ISBN ingresado.", "Información", JOptionPane.INFORMATION_MESSAGE);
            tblRegistroVentas.setVisible(false);
            return;
        }

        // Mostrar la tabla y cargar los datos
        tblRegistroVentas.setVisible(true);
        cargarDatosEnTabla(ventasPorIsbn, libroBuscado);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        try (PrintWriter writer = new PrintWriter(new File("VENTAS.CSV"))) {
            // Escribir los títulos de las columnas
            writer.println("Fecha;Cliente;Número de Factura;Cantidad;Precio de Venta;Total");

            // Escribir las filas de la tabla
            DefaultTableModel model = (DefaultTableModel) tblRegistroVentas.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                StringBuilder row = new StringBuilder();
                for (int j = 0; j < model.getColumnCount(); j++) {
                    row.append(model.getValueAt(i, j)).append(";");
                }
                writer.println(row.toString());
            }

            JOptionPane.showMessageDialog(this, "Datos exportados correctamente a VENTAS.CSV.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al exportar los datos: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportarActionPerformed
    private void cargarDatosEnTabla(List<Factura> ventasPorIsbn, Libro libroBuscado) {
        DefaultTableModel model = (DefaultTableModel) tblRegistroVentas.getModel();
        model.setRowCount(0);

        int totalCantidad = 0;
        double totalRecaudado = 0.0;
        double totalGanancias = 0.0;

        for (Factura factura : ventasPorIsbn) {
            for (String libroInfo : factura.getLibros()) {
                String[] partes = libroInfo.split("x ");
                if (partes.length > 1) {
                    int cantidad = Integer.parseInt(partes[0].trim());
                    String titulo = partes[1];

                    if (titulo.equals(libroBuscado.getTitulo())) {
                        double precioVenta = libroBuscado.getPrecioVenta();
                        double costo = libroBuscado.getPrecioCosto();
                        double total = precioVenta * cantidad;
                        double ganancia = (precioVenta - costo) * cantidad;

                        model.addRow(new Object[]{
                            factura.getFecha(),
                            factura.getCliente(),
                            factura.getNumeroFactura(),
                            cantidad,
                            precioVenta,
                            total
                        });

                        totalCantidad += cantidad;
                        totalRecaudado += total;
                        totalGanancias += ganancia;
                    }
                }
            }
        }

        lblCantEjemplaresVendidos.setText(String.valueOf(totalCantidad));
        lblCantTotalRecaudado.setText(String.format("$%.2f", totalRecaudado));
        lblCantTotalGanancia.setText(String.format("$%.2f", totalGanancias));
    }

    private void configurarTabla() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Fecha", "Cliente", "N° Factura", "Título", "Cantidad", "Precio Unitario", "Total"},
                0 // Inicialmente sin filas
        );
        tblRegistroVentas.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantEjemplaresVendidos;
    private javax.swing.JLabel lblCantTotalGanancia;
    private javax.swing.JLabel lblCantTotalRecaudado;
    private javax.swing.JLabel lblEjemplaresVendidos;
    private javax.swing.JLabel lblISBN;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JLabel lblTotalGanancia;
    private javax.swing.JLabel lblTotalRecaudado;
    private javax.swing.JTable tblRegistroVentas;
    private javax.swing.JTextField txtIsbn;
    // End of variables declaration//GEN-END:variables
}
