/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import dominio.Factura;
import dominio.Libro;
import javax.swing.JOptionPane;
/**
 *
 * @author vale_
 */
public class VentanaAnularVenta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAnularVenta
     */
    public VentanaAnularVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnularVenta = new javax.swing.JButton();
        txtNumFactura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Anular Venta");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Inserte el Num. de Factura:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 230, 15);

        btnAnularVenta.setText("Anular");
        btnAnularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnularVenta);
        btnAnularVenta.setBounds(200, 110, 110, 25);
        jPanel1.add(txtNumFactura);
        txtNumFactura.setBounds(210, 50, 100, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 310, 150);

        setBounds(0, 0, 372, 221);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularVentaActionPerformed
   String numeroFacturaStr = txtNumFactura.getText().trim();
    if (numeroFacturaStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingrese un número de factura.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int numeroFactura;
    try {
        numeroFactura = Integer.parseInt(numeroFacturaStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El número de factura debe ser un valor numérico.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Buscar la factura en el sistema (suponiendo que tienes un mapa global llamado FacturaManager.facturas)
    Factura factura = Factura.obtenerFactura(numeroFactura);
    if (factura == null) {
        JOptionPane.showMessageDialog(this, "La factura con el número ingresado no existe.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Mostrar los datos de la factura
    StringBuilder detalleFactura = new StringBuilder();
    detalleFactura.append("Factura Número: ").append(numeroFactura).append("\n")
                  .append("Fecha: ").append(factura.getFecha()).append("\n")
                  .append("Cliente: ").append(factura.getCliente()).append("\n")
                  .append("Total: $").append(String.format("%.2f", factura.getPrecioTotal())).append("\n")
                  .append("Libros:\n");

    for (String libroDetalle : factura.getLibros()) {
        detalleFactura.append("- ").append(libroDetalle).append("\n");
    }

    int confirmacion = JOptionPane.showConfirmDialog(this,
            "Detalles de la factura:\n" + detalleFactura.toString() +
            "\n¿Desea anular esta factura?", "Confirmación", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        // Reingresar los libros al stock
        for (String libroDetalle : factura.getLibros()) {
            String[] partes = libroDetalle.split("x ");
            int cantidad = Integer.parseInt(partes[0].trim());
            String tituloLibro = partes[1].trim();

            Libro libro = Libro.obtenerLibros().stream()
                    .filter(l -> l.getTitulo().equals(tituloLibro))
                    .findFirst()
                    .orElse(null);

            if (libro != null) {
                libro.setStock(libro.getStock() + cantidad);
            }
        }

        // Eliminar la factura del sistema
        Factura.eliminarFactura(numeroFactura);

        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, "La factura ha sido anulada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Limpiar el campo de texto
        txtNumFactura.setText("");
    }
    }//GEN-LAST:event_btnAnularVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAnularVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAnularVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNumFactura;
    // End of variables declaration//GEN-END:variables
}
