/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package interfaz;

import interfaz.consultas.VentanaConsultaLibros;
import interfaz.ventas.VentanaRegistrarVenta;
import interfaz.ventas.VentanaAnularVenta;
import interfaz.registro.VentanaAutor;
import interfaz.registro.VentanaLibro;
import interfaz.registro.VentanaEditorial;
import interfaz.registro.VentanaGenero;

/**
 *
 * @author macbookpro
 */
public class MenuObl extends javax.swing.JFrame {

    /**
     * Creates new form MenuObl
     */
    public MenuObl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        itmRegEditorial = new javax.swing.JMenu();
        itmRegistrarEditorial = new javax.swing.JMenuItem();
        itmRegistrarGenero = new javax.swing.JMenuItem();
        itmRegistrarAutor = new javax.swing.JMenuItem();
        itmRegistrarLibro = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        itmRegistrarVenta = new javax.swing.JMenuItem();
        itmAnularVenta = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        itmConsultaLibros = new javax.swing.JMenuItem();
        itmConsultaVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itmRegEditorial.setMnemonic('f');
        itmRegEditorial.setText("Registro");

        itmRegistrarEditorial.setMnemonic('o');
        itmRegistrarEditorial.setText("Registrar Editorial");
        itmRegistrarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistrarEditorialActionPerformed(evt);
            }
        });
        itmRegEditorial.add(itmRegistrarEditorial);

        itmRegistrarGenero.setMnemonic('s');
        itmRegistrarGenero.setText("Registrar Genero");
        itmRegistrarGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistrarGeneroActionPerformed(evt);
            }
        });
        itmRegEditorial.add(itmRegistrarGenero);

        itmRegistrarAutor.setMnemonic('a');
        itmRegistrarAutor.setText("Registrar Autor");
        itmRegistrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistrarAutorActionPerformed(evt);
            }
        });
        itmRegEditorial.add(itmRegistrarAutor);

        itmRegistrarLibro.setText("Registrar Libro");
        itmRegistrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistrarLibroActionPerformed(evt);
            }
        });
        itmRegEditorial.add(itmRegistrarLibro);

        menuBar.add(itmRegEditorial);

        editMenu.setMnemonic('e');
        editMenu.setText("Ventas");

        itmRegistrarVenta.setMnemonic('t');
        itmRegistrarVenta.setText("Registro Venta");
        itmRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRegistrarVentaActionPerformed(evt);
            }
        });
        editMenu.add(itmRegistrarVenta);

        itmAnularVenta.setMnemonic('y');
        itmAnularVenta.setText("Anular Venta");
        itmAnularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAnularVentaActionPerformed(evt);
            }
        });
        editMenu.add(itmAnularVenta);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Consultas");

        itmConsultaLibros.setMnemonic('c');
        itmConsultaLibros.setText("Consulta de Libros");
        itmConsultaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmConsultaLibrosActionPerformed(evt);
            }
        });
        helpMenu.add(itmConsultaLibros);

        itmConsultaVentas.setMnemonic('a');
        itmConsultaVentas.setText("Consulta de Ventas");
        helpMenu.add(itmConsultaVentas);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmRegistrarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistrarEditorialActionPerformed
        VentanaEditorial v = new VentanaEditorial();
        v.setVisible(true);
    }//GEN-LAST:event_itmRegistrarEditorialActionPerformed

    private void itmRegistrarGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistrarGeneroActionPerformed
        VentanaGenero v = new VentanaGenero();
        v.setVisible(true);
    }//GEN-LAST:event_itmRegistrarGeneroActionPerformed

    private void itmRegistrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistrarAutorActionPerformed
        VentanaAutor v = new VentanaAutor();
        v.setVisible(true);
    }//GEN-LAST:event_itmRegistrarAutorActionPerformed

    private void itmRegistrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistrarLibroActionPerformed
        VentanaLibro v = new VentanaLibro();
        v.setVisible(true);
    }//GEN-LAST:event_itmRegistrarLibroActionPerformed

    private void itmRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRegistrarVentaActionPerformed
        VentanaRegistrarVenta v = new VentanaRegistrarVenta();
        v.setVisible(true);
    }//GEN-LAST:event_itmRegistrarVentaActionPerformed

    private void itmAnularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAnularVentaActionPerformed
        VentanaAnularVenta v = new VentanaAnularVenta();
        v.setVisible(true);
    }//GEN-LAST:event_itmAnularVentaActionPerformed

    private void itmConsultaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmConsultaLibrosActionPerformed
        VentanaConsultaLibros v = new VentanaConsultaLibros();
        v.setVisible(true);
    }//GEN-LAST:event_itmConsultaLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuObl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuObl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuObl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuObl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuObl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem itmAnularVenta;
    private javax.swing.JMenuItem itmConsultaLibros;
    private javax.swing.JMenuItem itmConsultaVentas;
    private javax.swing.JMenu itmRegEditorial;
    private javax.swing.JMenuItem itmRegistrarAutor;
    private javax.swing.JMenuItem itmRegistrarEditorial;
    private javax.swing.JMenuItem itmRegistrarGenero;
    private javax.swing.JMenuItem itmRegistrarLibro;
    private javax.swing.JMenuItem itmRegistrarVenta;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
