/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author vale_
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnContinuarSesion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnNuevaSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("¿Deseas continuar con los datos guardados de la sesión anterior o iniciar una nueva sesión?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 480, 20);

        btnContinuarSesion.setText("Continuar Sesión");
        btnContinuarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuarSesion);
        btnContinuarSesion.setBounds(0, 70, 160, 25);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(410, 70, 100, 25);

        btnNuevaSesion.setText("Nueva sesión");
        btnNuevaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevaSesion);
        btnNuevaSesion.setBounds(170, 70, 160, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 510, 110);

        setBounds(0, 0, 568, 165);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarSesionActionPerformed
        // Abrir MenuObl para continuar con los datos guardados
        MenuObl menu = new MenuObl();
        menu.setVisible(true);
        this.dispose(); // Cerrar VentanaInicio        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarSesionActionPerformed

    private void btnNuevaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSesionActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "Esta acción borrará todos los datos guardados. ¿Deseas continuar?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            borrarArchivosDat(); // Borrar todos los archivos .dat
            MenuObl menu = new MenuObl(); // Abrir MenuObl para nueva sesión
            menu.setVisible(true);
            this.dispose(); // Cerrar VentanaInicio
        }
    }//GEN-LAST:event_btnNuevaSesionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed
    private void borrarArchivosDat() {
        File carpeta = new File(".");
        File[] archivosDat = carpeta.listFiles((dir, name) -> name.endsWith(".dat"));

        if (archivosDat != null) {
            for (File archivo : archivosDat) {
                if (archivo.delete()) {
                    System.out.println("Archivo borrado: " + archivo.getName());
                } else {
                    System.err.println("No se pudo borrar el archivo: " + archivo.getName());
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuarSesion;
    private javax.swing.JButton btnNuevaSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
