/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author vale_
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPreguntaInicio = new javax.swing.JLabel();
        btnResetearSistema = new javax.swing.JButton();
        btnComenzarNuevo = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        lblPreguntaInicio.setText("¿Desea resetear el sistema o comenzar uno completamente nuevo?");
        jPanel1.add(lblPreguntaInicio);
        lblPreguntaInicio.setBounds(40, 10, 327, 29);

        btnResetearSistema.setText("Resetear Sistema");
        btnResetearSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearSistemaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResetearSistema);
        btnResetearSistema.setBounds(0, 90, 154, 25);

        btnComenzarNuevo.setText("Comenzar Nuevo");
        btnComenzarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnComenzarNuevo);
        btnComenzarNuevo.setBounds(250, 90, 156, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(26, 12, 409, 121);

        setBounds(0, 0, 481, 184);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetearSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearSistemaActionPerformed
        System.out.println("Sistema reseteado.");
        this.setVisible(false); // Oculta la ventana de inicio

        // Abre el menú principal
        MenuObl menu = new MenuObl();
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetearSistemaActionPerformed

    private void btnComenzarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarNuevoActionPerformed
        System.out.println("Nuevo sistema iniciado.");
        this.setVisible(false); // Oculta la ventana de inicio

        // Abre el menú principal
        MenuObl menu = new MenuObl();
        menu.setVisible(true);
    }//GEN-LAST:event_btnComenzarNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzarNuevo;
    private javax.swing.JButton btnResetearSistema;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPreguntaInicio;
    // End of variables declaration//GEN-END:variables
}
